Revert "#if USE_x instead of #ifdef USE_x"
somehow this does not work in some cases:
arch/lpc21/mcu_periph/adc_arch.c:32:12: error: #if with no expression

This reverts commit c12f3401a082ef5b016f208a1b1ccd0fec0a3fd6.