Rename ACTUATORS_T4_UART_DEV to ACTUATORS_T4_UART_PORT
since build failure on semaphore test  gave:
modules/actuators/actuators_t4_uart.c:194:19: error: ‘ACTUATORS_T4_PORT’ undeclared